---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: admin-password
    secret-generator.v1.mittwald.de/length: "20"
stringData:
  admin-user: admin