---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap # This is important.  The snapshots with Kasten will fail with:
  #Failed to create Snapshot: CSI Driver failed to create snapshot for PVC (kubestr-csi-original-pvcl8mmp)
  # in Namespace (default): Failed to check and update snapshot content: failed to take snapshot
  # of the volume pvc-8da9919f-b541-4aad-b4ba-3b46e9ce24a9: "timestamp: nil Timestamp"  -  Error
  # 
  # See:
  # https://longhorn.io/docs/1.5.1/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/
