---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.25-192.168.0.150
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool-static
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.15-192.168.0.19
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2a
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-pool
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2a-static
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-pool-static
